experiment_info:
  # Main algorithm choices
  agent: rlcycle.dqn_base.agent.DQNBaseAgent
  learner: rlcycle.dqn_base.learner.DQNLearner
  loss: rlcycle.dqn_base.loss.DQNLoss
  action_selector: rlcycle.dqn_base.action_selector.DQNActionSelector
  device: cpu

  # Environment info
  env:
    name: "LunarLander-v2"
    is_atari: False
    max_episode_steps: 1000

  # Experiment default arguments:
  total_num_episodes: 1500
  test_interval: 100  # Test every 50 episodes
  test_num: 5  # Number of episodes to test during test phase
  render: True  # Render all episode steps
