model:
  state_dim: undefined
  action_dim: undefined

  log_std_min: -20
  log_std_max: 2
  
  critic:
    class: rlcycle.common.models.value.Critic
    params:
      model_cfg:
        fc:
          input:
            class: rlcycle.common.models.layers.LinearLayer
            params: 
              input_size: undefined
              output_size: 256
              post_activation_fn: relu           
          hidden:
            hidden1:
              class: rlcycle.common.models.layers.LinearLayer
              params: 
                input_size: 256
                output_size: 256
                post_activation_fn: relu
          output:
            class: rlcycle.common.models.layers.LinearLayer
            params:
              input_size: 256
              output_size: 1
              post_activation_fn: identity
              init_w: 0.003
  
  actor:
    class: rlcycle.common.models.policy.GaussianPolicy
    params:
      model_cfg:
        fc:
          input:
            class: rlcycle.common.models.layers.LinearLayer
            params: 
              input_size: undefined
              output_size: 256
              post_activation_fn: relu   
          
          hidden:
            hidden1:
              class: rlcycle.common.models.layers.LinearLayer
              params: 
                input_size: 256
                output_size: 256
                post_activation_fn: relu
          
          mu_stream:
            layer1:
              class: rlcycle.common.models.layers.LinearLayer
              params:
                input_size: 256
                output_size: undefined
                post_activation_fn: identity
                init_w: 0.003
          
          log_sigma_stream:
            layer1:
              class: rlcycle.common.models.layers.LinearLayer
              params:
                input_size: 256
                output_size: identity
                post_activation_fn: identity
                init_w: 0.003